print('..Building App')

pathToFiles = [
    'userInterface',
    'mainAlgorithm'
]


env = Environment(
    CC = 'g++',
    CCFLAGS = '-Wall',
    SCONS_CXX_STANDARD='c++11',
    CPPPATH = pathToFiles
    
)

SConscript('userInterface/SConscript', exports = 'env', duplicate = 0)
SConscript('mainAlgorithm/SConscript', exports = 'env', duplicate = 0)

env.Append(
    LIBS = [
        'userInterface',
        'evaluation'
    ],

    LIBPATH = pathToFiles

)

env.Program('cards', 'main.cpp')
